In [ ]:
import pandas as pd
prod=pd.Series([30,60,45,25],
index=["Wheat","Rice","Maize","Barley"])
print(prod)

Wheat     30
Rice      60
Maize     45
Barley    25
dtype: int64

In [ ]:
print(prod["Rice"])
print(prod.loc["Rice"])
print(prod.iloc[1])

60
60
60

In [ ]:
print(prod.max())
print(prod.sum())
print(prod.mean())
print(prod.idxmax())
print(prod.idxmin())

60
160
40.0
Rice
Barley

In [ ]:
increased_production=prod*1.10
print(increased_production)

Wheat     33.0
Rice      66.0
Maize     49.5
Barley    27.5
dtype: float64

In [ ]:
high_production=prod[prod>40]
print(high_production)
print(prod>40)

Rice     60
Maize    45
dtype: int64
Wheat     False
Rice       True
Maize      True
Barley    False
dtype: bool

In [ ]:
import pandas as pd
df=pd.DataFrame({
    "Name":['Akhil','Bobby','Charan'],
    "Age":[25,30,35],
    "City":["NY","LA","Chicago"]},
    index=["a","b","c"])
print(df)
print()
print(df.loc["b"])
print()
print(df.iloc[1])

     Name  Age     City
a   Akhil   25       NY
b   Bobby   30       LA
c  Charan   35  Chicago

Name    Bobby
Age        30
City       LA
Name: b, dtype: object

Name    Bobby
Age        30
City       LA
Name: b, dtype: object

In [4]:

import pandas as pd
df=pd.DataFrame({
    "Name":['Akhil','Bobby','Charan'],
    "Age":[25,30,35],
    "City":["NY","LA","Chicago"]},

    index=["a","b","c"],
)
print(df.loc[["a","c"],["Name","City"]])

     Name     City
a   Akhil       NY
c  Charan  Chicago

In [5]:
import pandas as pd
print(df.loc[df["Age"] > 28, ["Name" , "Age"]])

     Name  Age
b   Bobby   30
c  Charan   35

In [11]:
print(df.iloc[[0,2]])

     Name  Age     City
a   Akhil   25       NY
c  Charan   35  Chicago

In [26]:
print(df.iloc[[0,1,2],[0,2]])

     Name     City
a   Akhil       NY
b   Bobby       LA
c  Charan  Chicago

In [24]:
print(df.iloc[:] [:1])

    Name  Age City
a  Akhil   25   NY

In [49]:
import pandas as pd
data={
    "Farm":["Farm A","Farm B","Farm C","Farm D"],
    "Crop":["Wheat","Rice","Wheat","Maize"],
    "Area_in_hectares":[10,15,8,12],
    "Production_in_tons":[30,60,24,36]
}
df=pd.DataFrame(data,index=[1,2,3,4])
print(df)

     Farm   Crop  Area_in_hectares  Production_in_tons
1  Farm A  Wheat                10                  30
2  Farm B   Rice                15                  60
3  Farm C  Wheat                 8                  24
4  Farm D  Maize                12                  36

In [48]:
df.head(2)

     Farm   Crop  Area_in_hectares  Production_in_tons  Yield_ton_per_hectare
1  Farm A  Wheat                10                  30                    3.0
2  Farm B   Rice                15                  60                    4.0

In [47]:
df.tail(2)

     Farm   Crop  Area_in_hectares  Production_in_tons  Yield_ton_per_hectare
3  Farm C  Wheat                 8                  24                    3.0
4  Farm D  Maize                12                  36                    3.0

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, 1 to 4
Data columns (total 5 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Farm                   4 non-null      object
 1   Crop                   4 non-null      object
 2   Area_in_hectares       4 non-null      int64
 3   Production_in_tons     4 non-null      int64
 4   Yield_ton_per_hectare  4 non-null      float64
dtypes: float64(1), int64(2), object(2)
memory usage: 364.0+ bytes

In [45]:
df.describe()

       Area_in_hectares  Production_in_tons  Yield_ton_per_hectare
count          4.000000            4.000000                   4.00
mean          11.250000           37.500000                   3.25
std            2.986079           15.779734                   0.50
min            8.000000           24.000000                   3.00
25%            9.500000           28.500000                   3.00
50%           11.000000           33.000000                   3.00
75%           12.750000           42.000000                   3.25
max           15.000000           60.000000                   4.00

In [66]:
df["Yield_ton_per_hectare"]=df["Production_in_tons"]/df["Area_in_hectares"]
print(df)

     Farm   Crop  Area_in_hectares  Production_in_tons  Yield_ton_per_hectare
1  Farm A  Wheat                10                  30                    3.0
2  Farm B   Rice                15                  60                    4.0
3  Farm C  Wheat                 8                  24                    3.0
4  Farm D  Maize                12                  36                    3.0

In [67]:
print(df.loc[[1,3]])

     Farm   Crop  Area_in_hectares  Production_in_tons  Yield_ton_per_hectare
1  Farm A  Wheat                10                  30                    3.0
3  Farm C  Wheat                 8                  24                    3.0

In [68]:
print(df.loc[[1,3],[ "Farm", "Crop","Area_in_hectares" ,"Production_in_tons"]])

     Farm   Crop  Area_in_hectares  Production_in_tons
1  Farm A  Wheat                10                  30
3  Farm C  Wheat                 8                  24

In [69]:
print(df["Crop"]=="Wheat")
print()
wheat_farms=df[df["Crop"]=="Wheat"]
print(wheat_farms)

1     True
2    False
3     True
4    False
Name: Crop, dtype: bool

     Farm   Crop  Area_in_hectares  Production_in_tons  Yield_ton_per_hectare
1  Farm A  Wheat                10                  30                    3.0
3  Farm C  Wheat                 8                  24                    3.0

In [71]:
high_yield=df[df["Production_in_tons"]>35]
print(high_yield)

     Farm   Crop  Area_in_hectares  Production_in_tons  Yield_ton_per_hectare
2  Farm B   Rice                15                  60                    4.0
4  Farm D  Maize                12                  36                    3.0

In [70]:
sorted_df=df.sort_values(by="Production_in_tons",ascending=False)
print(sorted_df)

     Farm   Crop  Area_in_hectares  Production_in_tons  Yield_ton_per_hectare
2  Farm B   Rice                15                  60                    4.0
4  Farm D  Maize                12                  36                    3.0
1  Farm A  Wheat                10                  30                    3.0
3  Farm C  Wheat                 8                  24                    3.0

In [72]:
avg_yield=df.groupby("Crop")["Yield_ton_per_hectare"].mean()
print(avg_yield)

Crop
Maize    3.0
Rice     4.0
Wheat    3.0
Name: Yield_ton_per_hectare, dtype: float64